
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

use_frameworks!
inhibit_all_warnings!

platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MKCustomUIModule_Example' do
  pod 'MKCustomUIModule', :path => '../'

  target 'MKCustomUIModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
