use_frameworks!

platform :ios, '9.0'

target 'MKCustomUIModule_Example' do
  pod 'MKCustomUIModule', :path => '../'

  target 'MKCustomUIModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
